[logging]
log_to_stdout = true
stdout_log_level = "Info"
log_to_file = true
file_log_level = "Debug"
log_file_path = "/var/log/epic/epic-miner.log"
log_file_append = true

[mining]
algorithm = "RandomX"
run_tui = false
stratum_server_addr = "eu.epicmine.org:4444"
stratum_server_login = "pradana123.medium"
stratum_server_password = "pradana123m=pool"
stratum_server_tls_enabled = false

[mining.randomx_config]
threads = 4
jit = true
large_pages = false
hard_aes = true

[[mining.gpu_config]]
device = 0
driver = 2

[[mining.miner_plugin_config]]
plugin_name = "cuckatoo_lean_cpu_compat_19"
[mining.miner_plugin_config.parameters]
nthreads = 2
